backend:
    name: git-gateway
    branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "assets/uploads"
collections:
    - name: "blog"
      label: "Blog"
      folder: "_posts/"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "img", widget: "image", required: false }
          - { label: "Body", name: "content", widget: "markdown" }
          - { label: "Tags", name: tags", widget: "list", allow_add: true }
          - { label: "Publish Date", name: "date", widget: "datetime" }
