backend:
    name: git-gateway
    branch: admin
media_folder: "assets/uploads"
collections:
    - name: "blog"
      label: "Blog"
      folder: "_posts/"
      create: true
      slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
      editor:
          preview: false
      fields:
          - {
                label: "Layout",
                name: "layout",
                widget: "hidden",
                default: "blog",
            }
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Image", name: "img", widget: "image", required: false }
          - { label: "Body", name: "body", widget: "markdown" }
          - { label: "Tags", name: tags", widget: "list", allow_add: true }
          - { label: "Publish Date", name: "date", widget: "datetime" }
    - name: "site"
      label: "Site"
      editor:
          preview: False
      files:
          - label: "Team"
            name: "team"
            file: "_data/staff.yml"
            fields:
                - label: "Team members"
                  name: "items"
                  widget: "list"
                  fields:
                      - {
                            label: "Display Name",
                            name: "full_name",
                            widget: "string",
                        }
                      - {
                            label: "Active",
                            name: "active",
                            widget: "boolean",
                            required: false,
                        }
                      - {
                            label: "Title",
                            name: "title",
                            widget: "string",
                            required: false,
                        }
                      - {
                            label: "Image",
                            name: "img",
                            widget: "image",
                            required: false,
                        }
                      - {
                            label: "Mail",
                            name: "mail",
                            widget: "string",
                            required: false,
                        }
                      - {
                            label: "LinkedIn",
                            name: "linkedin",
                            widget: "string",
                            required: false,
                        }
                      - {
                            label: "Bio",
                            name: "text",
                            widget: "text",
                            required: false,
                        }
